version: "3.6"
services:
    ansible:
        image: fercsi/ansible-controller
        ports:
            - 22:22
        volumes:
            - ./work:/var/work
        container_name: controller
        hostname: controller
        restart: always
        depends_on:
            - host1
            - host2
            - host3
        networks:
            - default
            - private
    host1:
        image: fercsi/ansible-host
        ports:
            - 22:22
        container_name: host1
        hostname: host1
        restart: always
        networks:
            - private
    host2:
        image: fercsi/ansible-host
        ports:
            - 22:22
        container_name: host2
        hostname: host2
        restart: always
        networks:
            - private
    host3:
        image: fercsi/ansible-host
        ports:
            - 22:22
        container_name: host3
        hostname: host3
        restart: always
        networks:
            - private
networks:
    private:
        internal: true
