version: "3.6"
services:
    ansible:
        image: fercsi/ansible-playground:controller
        ports:
            - 22:22
        volumes:
            - ./work:/var/work
        container_name: controller
        hostname: controller
        restart: always
        depends_on:
            - host1
            - host2
            - host3
        environment:
          APG_HOSTS: host1 host2 host3
          APG_INVENTORY_GROUPS: h1 h2
          APG_INVGROUP_h1: host1
          APG_INVGROUP_h2: host2 host3
        networks:
            - default
            - private
    host1:
        image: fercsi/ansible-playground:host
        ports:
            - 22:22
        container_name: host1
        hostname: host1
        restart: always
        networks:
            - private
    host2:
        image: fercsi/ansible-playground:u22-host
        ports:
            - 22:22
        container_name: host2
        hostname: host2
        restart: always
        networks:
            - private
    host3:
        image: fercsi/ansible-playground:alma9-host
        ports:
            - 22:22
        container_name: host3
        hostname: host3
        restart: always
        networks:
            - private
networks:
    private:
        internal: true
