---
- name: Test template functionality
  hosts: host1
  gather_facts: no
  become: false
  tasks:
  - name: Import variables
    include_vars:
      file: values.yaml
  - name: Show value
    debug:
      msg: "{{dict}}"
  - name: Create template
    template:
      src: text.tplt
      dest: /text
      mode: 755
